#!/usr/bin/env bash
#
# ocfp test blacksmith env <name> services-create [redis|rabbitmq]
# wait....
# ocfp test blacksmith env <name> apps-push [redis|rabbitmq]
# ocfp test blacksmith env <name> apps-test [redis|rabbitmq]
# ocfp test blacksmith env <name> apps-delete [redis|rabbitmq]
# ocfp test blacksmith env <name> services-delete [redis|rabbitmq]
# party....
#

fail() { echo -e "\e[31mERROR:\e[0m $*" >&2 ; exit 1 ; }

run() { echo -e "\$ $*"; "$@"; }

_debug() { [[ -z ${DEBUG:-} ]] || echo -e "$*" >&2 ; }

_usage() {
  fail "Usage: ${0//*\/} <fetch|push|test|delete|setup|all> <space> [<space> ...]"
}

parse::args() {
  while [[ $# > 0 ]]
  do
    case $1 in
      (services-create|services-delete|apps-push|apps-test|apps-delete)
        action=${1}
        shift
        ;;
      (e|env)
        env=$2
        shift 2 || fail "Usage: ...env <name>"
        ;;
      (rabbitmq|redis|postgres)
        services+=( ${1} ) ; shift 1
        ;;
      (*)
        fail "Unknown arg: '$1'\nUsage: env <name> space <name> [space <name>...] <cmd>"
        ;;
    esac
  done

  [[ ${#services} > 0 ]] ||
    services=($( ls -1 ${apps_path} |
      grep -E 'cf-.*-example-app-master.zip' |
      sed -E 's/cf-(.*)-example-app-master.zip/\1/'
      ))
}

cf::login() {
  local env=$1
  ( cd ~/deployments/cf
    genesis ${env} do login
  ) || fail "Failed to login to ${env}!"
}
 
apps::fetch() {
  local service=$1
  local archive="cf-${service}-example-app-master.zip"
  if [[ ! -d ${apps_path}/${archive/.zip} ]]
  then
    if ! [[ -s ${apps_path}/${archive} ]]
    then
      ( cd ${apps_path}
        # curl -sOL ${RMQ_APP_URL}/${archive}
      )
    fi
    ( cd ${apps_path}
      run unzip /opt/ocfp/apps/${archive}
    )
  fi
}

app::push() {
  local service=$1
  for index in a b
  do
    local archive="cf-${service}-example-app-master.zip"
    run cf push test-${service}-app-${index} --random-route \
      -p ${apps_path}/${archive/.zip} \
      -f ${apps_path}/${archive/.zip}/manifest.yml
  done
}

apps::push() {
  local services=(redis rabbitmq) # TODO: let this be dynamically defined.
  for svc in ${services[@]}
  do app::push ${svc}
  done
}

apps::delete() {
  local services=(redis rabbitmq) # TODO: let this be dynamically defined.
  for svc in ${services[@]}
  do 
    for index in a b
    do run cf delete -f test-${svc}-app-${index}
    done
  done
}

apps::app::uri() {
  local app=$1 app_guid=$( cf app ${app} --guid )
  cf curl /v3/apps/${app_guid}/env |
    jq -r '.application_env_json.VCAP_APPLICATION.application_uris[0]'
}
 
apps::test() {
  local service=$1 plan=$2
  local service_instance=test-${service}-${plan}

  test::${service} ${service_instance}
}
 
apps::test::spaces() {
  local service=$1
  local plans=($( service::plans ${service} ))
  for plans in ${plans[@]}
  do apps::test ${space} ${service} ${plan}
  done
}

service::plans() {
  local service=$1
  cf curl "/v3/service_plans?service_offering_names=${service}" | jq -r '.resources[].name'
}

service::instances() {
  local service=$1 plan=$2
  local guid=$(service::plan::guid ${service} ${plan})
  cf curl "/v3/service_instances" | 
    jq -r '.resources[] | select(.relationships.service_plan.data.guid == "'${guid}'") | .name'
}

service::plan::guid() {
  local service=$1 plan=$2
  cf curl "/v3/service_plans?service_offering_names=${service}" |
    jq -r '.resources[] | select(.name == "${plan}") | .guid'
}

service::plans::create() {
  local service=$1 plan
  local -a plans=($( service::plans ${service} ))
  for plan in ${plans[@]}
  do
    run cf create-service ${service} ${plan} test-${service}-${plan}
  done
}

service::plans::delete() {
  local service=$1 plan
  local -a plans=($( service::plans ${service} ))
  for plan in ${plans[@]}
  do
    run cf delete-service ${service} ${plan} test-${service}-${plan}
  done
}

service::plans::bind() {
  local service=$1 plan
  local -a plans=($( service::plans ${service} ))
  for plan in ${plans[@]}
  do
    run cf bind-service test-${service}-app-a test-${service}-${plan}
    run cf restage test-${service}-app-a
  done
}

service::plans::unbind() {
  local service=$1 plan
  local -a plans=($( service::plans ${service} ))
  for plan in ${plans[@]}
  do
    run cf unbind-service test-${service}-app-a test-${service}-${plan}
    # run cf restage test-${service}-app-a # ???
  done
}

services::create() {
  local svc
  for svc in ${services[@]}
  do service::plans::create ${svc}
  done
}

services::delete() {
  local svc
  for svc in ${services[@]}
  do service::plans::delete ${svc}
  done
}

services::bind() {
  local svc
  for svc in ${services[@]}
  do service::plans::bind ${svc}
  done
}

services::unbind() {
  local svc
  for svc in ${services[@]}
  do service::plans::unbind ${svc}
  done
}

autoscaler::policy() {
  cat <<"EOF"
    {
      instance_min_count: 1,
      instance_max_count: 3,
      scaling_rules: [
        {
          metric_type: "${queue}_messages_ready",
          threshold: 1,
          operator: ">",
          adjustment: "+1"
        },
        {
          metric_type: "${queue}_messages_ready",
          threshold: 2,
          operator: "<",
          adjustment: "-1"
        }
      ]
    }
EOF
}

test::rabbitmq() {
  local service_instance=$1
  local app=$( apps::app::uri test-rabbitmq-app-a )
  local queue=test-rabbit-queue 

  echo -e "= RabbiMQ - Testing Queues - Non TLS"
  printf "%0.s=" {1..80}

  echo -e "Pinging the rabbitmq app via the app url..."
  run curl ${app}/ping

  echo -e "\nCreating queue ${queue}..."
  run curl -X POST ${app}/queues -d "name=${queue}"

  echo -e "\nListing queues..."
  run curl ${app}/queues

  echo -e "\nInserting a message into queue ${queue}..."
  run curl -X PUT ${app}/queue/${queue} -d 'data=hello'

  echo -e "\nGetting messages from queue ${queue}..."
  run curl -X GET ${app}/queue/${queue}

  printf "%0.s=" {1..80}
  echo -e "= RabbitMQ - Testing Queues - Enabling TLS for the app"
  printf "%0.s=" {1..80}

  cf set-env test-rabbitmq-app-a RABBITMQ_USE_SSL true
  run cf restage test-rabbitmq-app-a

  printf "%0.s=" {1..80}
  echo -e "= RabbitMQ - Testing Queues - TLS"
  printf "%0.s=" {1..80}

  echo -e "Pinging the rabbitmq app via the app url..."
  run curl ${app}/ping

  echo -e "\nCreating queue ${queue}..."
  run curl -X POST ${app}/queues -d "name=${queue}"

  echo -e "\nListing queues..."
  run curl ${app}/queues

  echo -e "\nInserting a message into queue ${queue}..."
  run curl -X PUT ${app}/queue/${queue} -d 'data=hello'

  echo -e "\nGetting messages from queue ${queue}..."
  run curl -X GET ${app}/queue/${queue}

  printf "%0.s=" {1..80}
  echo -e "= RabbitMQ - Testing Queues - Dynamic Credentials"
  printf "%0.s=" {1..80}

  run cf bind-service test-rabbitmq-app-b ${service_instance}
  run cf restage test-rabbitmq-app-b

  app_a_guid=$(cf app test-rabbitmq-app-a --guid)
  app_a_username=$( cf curl /v3/apps/${app_a_guid}/env |
    jq -r '.system_env_json.VCAP_SERVICES.rabbitmq[0].credentials.username'
  )

  app_b_guid=$(cf app test-rabbitmq-app-b --guid)
  app_b_username=$( cf curl /v3/apps/${app_b_guid}/env |
    jq -r '.system_env_json.VCAP_SERVICES.rabbitmq[0].credentials.username'
  )

  if [[ ${app_a_username} == ${app_b_username} ]]
  then echo "FAIL: The username for the service instance is the same for both apps!"
  else echo "PASS: The username for the service instance is not the same for both apps!"
  fi

  run cf create-service-key ${service_instance} rabbitmq-user-a
  run cf create-service-key ${service_instance} rabbitmq-user-b

  app_a_username=$( cf curl /v3/apps/${app_a_guid}/env |
    jq -r '.system_env_json.VCAP_SERVICES.rabbitmq[0].credentials.username'
  )
  app_b_username=$( cf curl /v3/apps/${app_b_guid}/env |
    jq -r '.system_env_json.VCAP_SERVICES.rabbitmq[0].credentials.username'
  )

  sk_a_guid=$(cf service-key ${service_instance} rabbitmq-user-a --guid)
  sk_a_username=$(cf curl /v2/service_keys/${sk_a_guid} | jq -r '.entity.credentials.username')

  sk_b_guid=$(cf service-key ${service_instance} rabbitmq-user-b --guid)
  sk_b_username=$(cf curl /v2/service_keys/${sk_b_guid} | jq -r '.entity.credentials.username')

  if [[ ${sk_a_username} == ${sk_b_username} ]]
  then echo "FAIL: The username for the service key is the same for both apps!"
  else echo "PASS: The username for the service key is not the same for both apps!"
  fi

  printf "%0.s=" {1..80}
  echo -e "= RabbitMQ - Testing Queues - Autoscaling based on Queue Depth"
  printf "%0.s=" {1..80}

  run cf create-service autoscaler autoscaler-free-plan test-rabbitmq-autoscaler

  run cf bind-service test-rabbitmq-app-a test-rabbitmq-autoscaler \
    -c "$( autoscaler::policy )"

  echo -e "Restaging in preparation of testing autoscaling-history..."
  run cf restage test-rabbitmq-app-a

  echo -e "Starting app state..."
  run cf app test-rabbitmq-app-a

  echo -e "Inserting 10 messages into the queue '${queue}'..."
  for i in {1..10}
  do run curl -X PUT ${app}/queue/${queue} -d "data=ciao-$i"
  done
  
  echo -e "Monitoring autoscaling-history for 5 minutes..."
  for i in {1..10}
  do
    run cf autoscaling-history test-rabbitmq-app-a
    echo -e "Sleeping for 30 seconds..."
    sleep 30
  done
}

test::redis() {
  local service_instance=$1 cmd app_url app_guid
  declare -a cmds

  printf "%0.s=" {1..80}
  printf "= Redis - Testing - TLS & Non-TLS"
  printf "%0.s=" {1..80}
  
  # TODO: missing binding between app and service.

  app_url="https://$( apps::app::uri test-redis-app-a )"
  app_guid=$( cf app test-redis-app-a --guid )

  echo -e "\nInserting a Key/Value pair into Redis, key 'foo'..."
  run curl -k -X PUT ${app_url}/foo -d "data=bar"

  echo -e "\nRetrieving the value for the key 'foo' non TLS..."
  run curl -k ${app_url}/foo

  echo -e "\nRetrieving the value for the key 'foo' via TLS..."
  run curl -k ${app_url}/tls/v1.2/foo

  printf "%0.s=" {1..80}
  echo -e "= Redis - Testing Disabled Commands"
  printf "%0.s=" {1..80}

  redis_ip=$(
  cf curl /v3/apps/${app_guid}/env |
    jq -r '.application_env_json.VCAP_SERVICES.redis[0].credentials.host'
  )

  redis_password=$(
  cf curl /v3/apps/${app_guid}/env |
    jq -r '.application_env_json.VCAP_SERVICES.redis[0].credentials.password'
  )

  redis-cli AUTH ${redis_password}

  cmds=( CONFIG SAVE BGSAVE DEBUG SHUTDOWN SLAVEOF SYNC ACL )
  for cmd in ${cmds[@]}
  do
    response=$(redis-cli -h ${redis_ip} -p 6379 ${cmd})
    if [[ ${response} =~ *ERR* ]]
    then echo -e "\n- Redis ${cmd} command is disabled"
    else echo -e "\n- Redis ${cmd} command is enabled"
    fi
  done
}
 
declare -a services apps spaces
declare \
  apps_path=${OCFP_PROJECT_PATH:-${HOME}/apps} \
  org=system \
  space=test-blacksmith-services \
  action

mkdir -p ${apps_path} && cd ${apps_path}

parse::args "$@"

cf::login ${env}

# TODO: let this be dynamically defined.
apps::fetch redis
apps::fetch rabbitmq

run cf target -o ${org} -s ${space}

case ${action} in
  (services-create)
    service::plans::create
    ;;
  (services-delete)
    service::plans::delete
    ;;
  (apps-push)
    apps::push
    ;;
  (apps-test)
    apps::test
    ;;
  (apps-delete)
    apps::delete
    ;;
  (*) _usage ;;
esac
 
exit 0
