#!/usr/bin/env bash
#
# Author Wayne E. Seguin
#

################################################################################
# Functions
################################################################################

fail() { echo -e "\e[31mERROR:\e[0m $*" >&2 ; exit 1 ; }

run()  { echo -e "\e[32m\$\e[0m $*"; "$@"; }

debug() { [[ -z ${DEBUG:-} ]] || echo -e "\e[93mDEBUG\e[0m: $*" >&2 ; }

usage() {
  echo -e "Usage: ${0//*\/} type <cloud|cpi> env <name> region <name> iaas <name> [bosh <env>]  [scale <dev|prod>] [vault-prefix <secret/...>] [dep <name>]" >&2
}

script::pwd() { 
  (
		cd -P "$( dirname "${1}" )" &> /dev/null 
		pwd
  )
}

script::path() {
  (
    local dir src="${BASH_SOURCE[0]:-$0}"
		while [[ -h "${src}" ]]
		do
			dir="$( script::pwd "${src}" )"
			src="$( readlink "${src}" )"
			[[ "${src%${src#?}}" == '/' ]] || src="${dir}/${src}"
		done
		script::pwd "${src}"
  )
}

scripts::path() {
  dirname "$( script::path )"
}

args::parse() {
  debug "${FUNCNAME[0]}: $*"

  local _action

  while [[ $# > 0 ]]
  do
    _action="${1}" ; shift
    case ${_action} in
      (kit) # Unused, but we won't error if it's given
        export OCFP_KIT=$1
        shift || fail "${0//*/} ... kit <name>"
        ;;
      (type) 
        config_type="${1}"
        shift || fail "${0//*/} ... config <type>"
        ;;
      (env)
        export OCFP_ENV_NAME=${1//.yml}
        shift || fail "${0//*/} ... name <env-name> # ex: ocfp-codex-mgmt-us-east-1 / ocfp-codex-us-east-1"
        ;;
      (dep)
        deps+=( "${1//.yml}" )
        shift || fail "${0//*/} ... dep <env-name>"
        ;;
      (vault-prefix)
        export OCFP_VAULT_PREFIX="${1}" # override default of secret/
        shift || fail "${0//*/} ... vault-prefix \"secret/...\""
        ;;
      (region)
        export OCFP_REGION=$1 # ex: us-east-1, us-west-2
        shift || fail "${0//*/} ... region <region>"
        ;;
      (iaas)
        export OCFP_IAAS="$1"
        shift || fail "${0//*/} ... iaas <aws|azure|gcp|openstack|vsphere|warden>"
        case ${OCFP_IAAS} in
          #NOTE: Upstream are alicloud aws azure cloudstack docker gcp openstack softlayer vcloud virtualbox vsphere warden
          (aws|azure|gcp|openstack|vsphere|warden) true ;;
          (*) fail "Unsupported IAAS type: ${OCFP_IAAS}" ;;
        esac
        ;;
      (bosh)
        export OCFP_BOSH_ENV="$1"
        shift || fail "${0//*/} ... bosh <bosh-env-name>"
        ;;
      (scale) 
        config_scale="${1}"
        shift || fail "${0//*/} ... scale <type>"
        ;;
      (*)
        usage
        ;;
    esac
  done

  [[ -n ${OCFP_ENV_NAME} ]] || fail "'env <name>' must be given"
  [[ -n ${config_type} ]]   || fail "'type <cloud|cpi>' must be given"
  [[ -n ${OCFP_REGION} ]]   || fail "'region <region>' must be given"
  [[ -n ${OCFP_IAAS} ]]     || fail "'iaas <aws|gcp|azure>' must be given"

  set::env::type

  # All envs need to know their deployer/bosh_env, mgmt bosh is the exception
  [[ ${env_type} == "mgmt" ]] || [[ -n ${OCFP_BOSH_ENV} ]] ||
    fail "'bosh <bosh-env-name>' must be given"
}

set::env::type() {
  debug "${FUNCNAME[0]}: $*"

  case "${OCFP_ENV_NAME}" in
    (*-mgmt-*) env_type="mgmt" ;;
    (*)        env_type="ocf"  ;;
  esac
  export OCFP_ENV_TYPE="${env_type}"
}

init::config::cloud() {
  debug "${FUNCNAME[0]}: $*"

  local _config_path="${scripts_path}/templates/configs/${config_type}/${OCFP_IAAS}"
  local _meta="${scripts_path}/templates/configs/${config_type}/meta.yml"
  local _meta_prune="${scripts_path}/templates/configs/meta-prune.yml"
  local _target="configs/${config_type}/${OCFP_ENV_NAME}.yml"

  echo -e "Generating ${config_type} Config File for ${env_type} env with scale ${config_scale:-"dev"}...\n\t-> ${_target}"

  export OCFP_ENV_SCALE=${config_scale:-"dev"}

  declare -a _merge

  _merge=(
    "${_meta}"
    "${scripts_path}/templates/configs/cloud/meta/${env_type}.yml"
    "${_config_path}/scale/${env_type}.yml"
    "${_config_path}/${env_type}.yml"
  )

  _tmp_path=$(mktemp -d 2>/dev/null || mktemp -d -t 'ocfp')

  for dep in "${deps[@]}"
  do
    _dep_env="${dep%%@*}" # vault mount override via @<vault-mount>
    ( # Subshell so as to not clobber parents env vars
      case ${dep} in
        (*\@*) _vault_prefix="${dep##*\@}" ;;
        (*)    _vault_prefix="${OCFP_VAULT_PREFIX}" ;;
      esac

      # Override vault paths for dependent env
      OCFP_VAULT_ENV_PATH="${_vault_prefix}/${_dep_env//-/\/}"
      OCFP_VAULT_TF_PATH="${_vault_prefix}/tf/${_dep_env//-/\/}"
      OCFP_ENV_NAME="${_dep_env}"
      OCFP_ENV_TYPE="ocf"
      VAULT_PREFIX="${_vault_prefix}"

      _m=(
      "${_meta}"
      "${scripts_path}/templates/configs/cloud/meta/ocf.yml"
      "${_config_path}/azs/ocf.yml"
      "${_config_path}/networks/ocf-bosh.yml"
      "${_meta_prune}"
      )
      spruce merge -m "${_m[@]}" > "${_tmp_path}/${_dep_env}.yml"
    )
    _merge+=( "${_tmp_path}/${_dep_env}.yml" ) 
  done

  _merge+=( "${_meta_prune}")

  spruce merge -m "${_merge[@]}" > "${_target}"
}

init::config::cpi() {
  debug "${FUNCNAME[0]}: $*"

  local _src_path _dst_path

  _src_path="${OCFP_VAULT_PREFIX}/iam/${env_type}"
  _dst_path="${OCFP_VAULT_ENV_PATH}/bosh"

  local _target="configs/${config_type}/${OCFP_ENV_NAME}.yml"
  local _config_path="${scripts_path}/templates/configs/${config_type}"
  local _template="${_config_path}/${env_type}.yml"
  local _meta="${scripts_path}/templates/configs/${config_type}/meta.yml"
  local _meta_prune="${scripts_path}/templates/configs/meta-prune.yml"

  echo -e "Generating ${config_type} Config File for ${env_type} env with scale ${config_scale:-"dev"}...\n\t-> ${_target}"

  export OCFP_ENV_SCALE=${config_scale:-"dev"}

  declare -a _merge

  _merge=( "${_meta}" "${_template}" )

  local _tmp_path=$(mktemp -d 2>/dev/null || mktemp -d -t 'ocfp')

  for dep in "${deps[@]}" ; do
    _dep_env="${dep%%@*}" # vault mount override via @<vault-mount>
    ( # Subshell so as to not clobber parents env vars
      case ${dep} in
        (*\@*) _vault_prefix="${dep##*\@}" ;;
        (*)    _vault_prefix="${OCFP_VAULT_PREFIX}" ;;
      esac
      # Override vault paths for dependent env
      OCFP_VAULT_ENV_PATH="${_vault_prefix}/${_dep_env//-/\/}"
      OCFP_VAULT_TF_PATH="${_vault_prefix}/tf/${_dep_env//-/\/}"
      OCFP_ENV_NAME="${_dep_env}"
      VAULT_PREFIX="${_vault_prefix}"
      local _m=(
        "${_meta}"
        "${_config_path}/ocf.yml"
        "${_meta_prune}"
      )
      spruce merge -m "${_m[@]}" > "${_tmp_path}/${_dep_env}.yml"
    )
    _merge+=( "${_tmp_path}/${_dep_env}.yml" ) 
  done

  _merge+=( "${_meta_prune}")

  spruce merge -m "${_merge[@]}" > "${_target}"
}

################################################################################
# Main
################################################################################

declare config_type scripts_path

args::parse "$@"

scripts_path=$(scripts::path)

mkdir -p "configs/${config_type}"

case ${config_type} in 
  (cloud) init::config::cloud "$@" ;;
  (cpi)   init::config::cpi "$@" ;;
  (*)     fail "config type must be cloud or cpi not '${config_type}'" ;;
esac

exit $?
