#!/usr/bin/env bash

fail() { echo -e "$*" >&2 ; exit 1 ; }

[[ -n ${OCFP_REGION:-} ]]   || fail "OCFP_REGION   must be set and exported."
[[ -n ${OCFP_ENV_NAME:-} ]] || fail "OCFP_ENV_NAME must be set and exported."

usage() {
  echo -e "$(cat <<EOT

USAGE

  $ export OCFP_REGION="..." OCFP_ENV_NAME="..." 
  $ ${0}

EOT
)" >&2
exit 1
}

fail() { echo -e "$*" >&2 ; exit 1 ; }

shift || usage

cat <<-YAML
---
kit:
  name: blacksmith
  version: 0.12.1-rc.14
  features:
  - (( append ))
  - external-bosh # -vault???
  - bosh-dns-health-check
  - broker-tls
  #- redis-tls
  #- redis-dual-mode
  #- rabbitmq
  #- rabbitmq-tls
  #- rabbitmq-dual-mode
  #- rabbitmq-dashboard-registration
  #- postgresql
YAML

cat <<-YAML

genesis:
  env: ${OCFP_ENV_NAME}
  min_version: 2.8.5
YAML

case ${OCFP_VAULT_PREFIX} in
  (secret/*) echo "  secrets_mount: \"${OCFP_VAULT_PREFIX}\"" ;;
  (*) true ;;
esac

cat <<-YAML

exodus:
  broker_url: (( concat "https://" params.fqdn ))

meta:
  vault_tf: (( concat meta.vault_aws "/${OCFP_REGION//-/\/}" ))
  ...plans...

params:
  env: ${OCFP_ENV_NAME}
  ip: (( vault meta.vault_tf "ocfp/ocf/blacksmith:ip" )) # Computed in TF cidrhost(ocfp/1,5
  fqdn: (( vault meta.vault "ocfp/ocf/blacksmith:dns" ))

  # blacksmith_debug: true

  #TODO: Do we need to pass in the external bosh director IP???
  #boshdir_ip: (( vault meta.vault_tf "ocfp/mgmt/bosh:ip" )) #cidrhost(ocfp/1, 4) -> should be `.4` - validate, this might need to be ,5 if it computes from 0

  # TODO: SHIELD Backups..

YAML


