#!/usr/bin/env bash

fail() { echo -e "$*" >&2 ; exit 1 ; }

[[ -n ${OCFP_REGION:-} ]]   || fail "OCFP_REGION   must be set and exported."
[[ -n ${OCFP_ENV_NAME:-} ]] || fail "OCFP_ENV_NAME must be set and exported."
[[ -n ${OCFP_VAULT_ENV_PREFIX:-} ]] || fail "OCFP_VAULT_ENV_PREFIX must be set and exported."
[[ -n ${OCFP_VAULT_TF_PREFIX:-} ]] || fail "OCFP_VAULT_ENV_PREFIX must be set and exported."

case "${OCFP_ENV_NAME}" in
  (*-mgmt-*) env_type="mgmt" ;;
  (*)        env_type="ocf" ;;
esac

usage() {
  echo -e "$(cat <<EOT

USAGE

  $ export OCFP_REGION="..." OCFP_ENV_NAME="..." 
  $ ${0}

EOT
)" >&2
exit 1
}

fail() { echo -e "$*" >&2 ; exit 1 ; }

cat <<-YAML
---
kit:
  name: blacksmith
  version: 0.12.1-rc.14
  features:
  - (( append ))
  - ocfp
  #- bosh-dns-health-check
  #- broker-tls
  #- redis-tls
  #- redis-dual-mode
  #- rabbitmq
  #- rabbitmq-tls
  #- rabbitmq-dual-mode
  #- rabbitmq-dashboard-registration
  #- postgresql
YAML

cat <<-YAML

genesis:
  env: ${OCFP_ENV_NAME}
  min_version: 2.8.5
YAML

case ${OCFP_VAULT_PREFIX} in
  (secret/*) echo "  secrets_mount: \"${OCFP_VAULT_PREFIX}\"" ;;
  (*) true ;;
esac

cat <<-YAML

exodus:
  broker_url: (( concat "https://" params.fqdn ))

meta:
  vault_tf: (( concat ${OCFP_VAULT_PREFIX:-"secret"} "/${OCFP_REGION//-/\/}" ))
  TODO: ...plans...

params:
  env: ${OCFP_ENV_NAME}
  ip: (( vault meta.vault_tf "ocfp/${env_type}/net/blacksmith:ip" ))
  fqdn: (( vault meta.vault_tf "ocfp/${env_type}/net/blacksmith:fqdn" ))

  # blacksmith_debug: true

  #TODO: Do we need to pass in the external bosh director IP???
  #boshdir_ip: (( vault meta.vault_tf "ocfp/${env_type}/net/bosh:ip" ))

  # TODO: SHIELD Backups..

  # TODO: Plans

YAML


