#!/usr/bin/env bash

fail() { echo -e "$*" >&2 ; exit 1 ; }

[[ -n ${OCFP_IAAS:-} ]]     || fail "OCFP_IAAS must be set and exported."
[[ -n ${OCFP_REGION:-} ]]   || fail "OCFP_REGION must be set and exported."
[[ -n ${OCFP_ENV_NAME:-} ]] || fail "OCFP_ENV_NAME must be set and exported."
[[ -n ${OCFP_BOSH_ENV:-} ]] || fail "OCFP_BOSH_ENV must be set and exported."


case "${OCFP_ENV_NAME}" in
  (*-mgmt-*) env_type="mgmt" ;;
  (*)        env_type="ocf" ;;
esac

usage() {
  echo -e "$(cat <<EOT

USAGE

  $ export OCFP_REGION="..." OCFP_ENV_NAME="..." 
  $ ${0}

EOT
)" >&2
exit 1
}

fail() { echo -e "$*" >&2 ; exit 1 ; }

cat <<-YAML
---
kit:
  name: blacksmith
  version: 0.12.1-rc.14
  features:
  - (( append ))
  - ${OCFP_IAAS}
  - ocfp
  #- bosh-dns-health-check
  #- broker-tls
  #- redis-tls
  #- redis-dual-mode
  #- rabbitmq
  #- rabbitmq-tls
  #- rabbitmq-dual-mode
  #- rabbitmq-dashboard-registration
  #- postgresql
YAML

cat <<-YAML

genesis:
  env: ${OCFP_ENV_NAME}
  min_version: 2.8.5
  bosh_env: ${OCFP_BOSH_ENV} # <bosh-env>[@/secret{mount-path}/exodus/] that deploys this env
YAML

case ${OCFP_VAULT_PREFIX:-} in
  (secret*) echo "  secrets_mount: \"${OCFP_VAULT_PREFIX}\"" ;;
  (*) true ;;
esac

cat <<-YAML

params:
#  ocfp:
#    env:
#      scale: "prod" # default is "dev"
  dns_cache: true # DNS Caching (for runtime config)

YAML

