#!/usr/bin/env bash

fail() { echo -e "$*" >&2 ; exit 1 ; }

[[ -n ${OCFP_IAAS:-} ]]     || fail "OCFP_IAAS must be set and exported."
[[ -n ${OCFP_ENV_NAME:-} ]] || fail "OCFP_ENV_NAME must be set and exported."
[[ -n ${OCFP_BOSH_ENV:-} ]] || fail "OCFP_BOSH_ENV must be set and exported."

usage() {
  echo -e "$(cat <<EOT

USAGE

  $ export OCFP_IAAS="..." OCFP_ENV_NAME="..." OCFP_BOSH_ENV="..."
  $ ${0}

EOT
)" >&2
exit 1
}

fail() { echo -e "$*" >&2 ; exit 1 ; }

cat <<-YAML
---
kit:
  name: cf
  version: 2.2.1-rc.5
  features:
  - (( append ))
  - ${OCFP_IAAS}
  - ocfp

genesis:
  min_version: 2.8.5 # TODO: update to 2.8.6 when released
  env: ${OCFP_ENV_NAME}
  bosh_env: ${OCFP_BOSH_ENV} # <bosh-env>[@/secret{mount-path}/exodus/] that deploys this env
YAML

case ${OCFP_VAULT_PREFIX:-} in
  (secret*) echo "  secrets_mount: \"${OCFP_VAULT_PREFIX}\"" ;;
  (*) true ;;
esac

cat <<-YAML

params:
# ocfp_env_scale: "prod" # default is "dev"
  dns_cache: true # DNS Caching (for runtime config)
YAML

