#!/usr/bin/env bash

fail() { echo -e "$*" >&2 ; exit 1 ; }

[[ -n ${OCFP_IAAS:-} ]]     || fail "OCFP_IAAS must be set and exported."
[[ -n ${OCFP_REGION:-} ]]   || fail "OCFP_REGION must be set and exported."
[[ -n ${OCFP_ENV_NAME:-} ]] || fail "OCFP_ENV_NAME must be set and exported."
[[ -n ${OCFP_BOSH_ENV:-} ]] || fail "OCFP_BOSH_ENV must be set and exported."

usage() {
  echo -e "$(cat <<EOT

USAGE

  $ export OCFP_REGION="..." OCFP_ENV_NAME="..." 
  $ ${0}

EOT
)" >&2
exit 1
}

fail() { echo -e "$*" >&2 ; exit 1 ; }

cat <<-YAML
---
kit:
  name: concourse
  version: 4.1.4
  features:
  - (( append ))
  - ${OCFP_IAAS}
  - ocfp

genesis:
  env: ${OCFP_ENV_NAME}
  min_version: 2.8.5 # TODO: update to 2.8.6 when released
  bosh_env: ${OCFP_BOSH_ENV} # <bosh-env>[@/secret{mount-path}/exodus/] that deploys this env
YAML

case ${OCFP_VAULT_PREFIX:-} in
  (secret/*) echo "  secrets_mount: \"${OCFP_VAULT_PREFIX}\"" ;;
  (*) true ;;
esac

cat <<-YAML

params:
#  ocfp:
#    env:
#      scale: "prod" # default is "dev"
  dns_cache: true # DNS Caching (for runtime config)
YAML

