#!/usr/bin/env bash

fail() { echo -e "$*" >&2 ; exit 1 ; }

[[ -n ${OCFP_REGION:-} ]]   || fail "OCFP_REGION   must be set and exported."
[[ -n ${OCFP_ENV_NAME:-} ]] || fail "OCFP_ENV_NAME must be set and exported."

usage() {
  echo -e "$(cat <<EOT

USAGE

  $ export OCFP_REGION="..." OCFP_ENV_NAME="..." 
  $ ${0}

EOT
)" >&2
exit 1
}

fail() { echo -e "$*" >&2 ; exit 1 ; }

cat <<-YAML
---
kit:
  name: vault
  version: 2.0.0.rc.7
  features:
  - (( append ))
  - ocfp

genesis:
  env: ${OCFP_ENV_NAME}
  bosh_env: ${OCFP_ENV_NAME}
  min_version: 2.8.5
YAML

case ${OCFP_VAULT_PREFIX} in
  (secret/*) echo "  secrets_mount: \"${OCFP_VAULT_PREFIX}\"" ;;
  (*) true ;;
esac

cat <<-YAML

meta:
  vault_tf: (( concat ${OCFP_VAULT_PREFIX:-"secret"} "/${OCFP_REGION//-/\/}" ))

YAML

